[tool.ruff]
line-length = 79
show-fixes = true

[tool.ruff.format]
docstring-code-format = false
line-ending = "lf"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]

[tool.mypy]
explicit_package_bases = true
warn_return_any = true
no_implicit_optional = true
disallow_untyped_calls = true
disallow_untyped_defs = true
ignore_missing_imports = true
follow_imports = 'skip'
exclude = ['^venv/*']